In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader

In [3]:
import numpy as np

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [5]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [21]:
train_ds=TensorDataset(inputs,targets)
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [22]:
#create models
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2480, -0.5486,  0.3967],
        [ 0.0579, -0.0037, -0.1194]], requires_grad=True)
Parameter containing:
tensor([-0.3466, -0.0209], requires_grad=True)


In [23]:
#make predictions
preds=model(inputs)
print(preds)
print(targets)

tensor([[ -1.9385,  -1.1774],
        [ -0.6640,  -2.7205],
        [-29.2723,  -2.4044],
        [ 16.0413,   1.3051],
        [ -8.1298,  -4.7392],
        [ -1.9385,  -1.1774],
        [ -0.6640,  -2.7205],
        [-29.2723,  -2.4044],
        [ 16.0413,   1.3051],
        [ -8.1298,  -4.7392],
        [ -1.9385,  -1.1774],
        [ -0.6640,  -2.7205],
        [-29.2723,  -2.4044],
        [ 16.0413,   1.3051],
        [ -8.1298,  -4.7392]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [24]:
#calculate loss
import torch.nn.functional as F
loss_fn=F.mse_loss
loss=loss_fn(preds,targets)
print(loss)

tensor(9513.9902, grad_fn=<MseLossBackward>)


In [25]:
#create and optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [26]:
#now train the model
def train(model,epoch_size,loss_fn,opt):
    for epoch in range(100):
        for x,y in train_dl:
            pred=model(x)
            loss=loss_fn(pred,y)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1)%10==0:
            print('epoch[{}/{}],Loss:{:.4f}'.format((epoch+1),epoch_size,loss.item()))

In [28]:
#training the model
epoch_size=200
train(model,epoch_size,loss_fn,opt)

epoch[10/200],Loss:25.8621
epoch[20/200],Loss:26.3827
epoch[30/200],Loss:22.8058
epoch[40/200],Loss:14.9942
epoch[50/200],Loss:15.2208
epoch[60/200],Loss:8.3826
epoch[70/200],Loss:14.1352
epoch[80/200],Loss:7.8111
epoch[90/200],Loss:10.4179
epoch[100/200],Loss:7.6874


In [29]:
#making predictions
pred=model(inputs)
print(pred)
print(targets)

tensor([[ 57.2925,  70.9360],
        [ 82.7647,  98.1545],
        [117.1641, 138.5503],
        [ 22.2532,  39.6844],
        [102.1419, 113.1364],
        [ 57.2925,  70.9360],
        [ 82.7647,  98.1545],
        [117.1641, 138.5503],
        [ 22.2532,  39.6844],
        [102.1419, 113.1364],
        [ 57.2925,  70.9360],
        [ 82.7647,  98.1545],
        [117.1641, 138.5503],
        [ 22.2532,  39.6844],
        [102.1419, 113.1364]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
