# Linear Regression In PyTorch from scratch


In [1]:
import torch
import math
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
#Initialize weights and bias with random integers
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.2322, -0.7998, -0.6060],
        [-1.6483,  0.8323,  0.3154]], requires_grad=True)
tensor([1.6388, 0.4497], requires_grad=True)


In [6]:
#create a linear regression model
def model(x):
    return x @ w.t() + b

In [7]:
#make predictions
preds=model(inputs)
print(preds)
print(targets)

tensor([[-167.9616,  -50.5467],
        [-219.6647,  -56.1133],
        [-247.8914,  -13.1253],
        [-180.8643, -120.2155],
        [-202.5904,  -11.2998]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
#define a loss function ie mean squared error
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff**2)/diff.numel()

In [9]:
#calculate loss
loss=mse(targets,preds)
print(math.sqrt(loss))

226.26759254807126


In [10]:
#compute gradient
loss.backward()

In [11]:
#gradients for weight
print(w.grad)
print(b.grad)

tensor([[-23481.4258, -25737.4434, -15809.9805],
        [-12167.3574, -12150.4883,  -7730.3970]])
tensor([-279.9945, -142.2601])


In [12]:
#adjust weight and bias using graidents
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()


In [13]:
print(w)
print(b)

tensor([[-0.9974, -0.5424, -0.4479],
        [-1.5266,  0.9538,  0.3927]], requires_grad=True)
tensor([1.6416, 0.4511], requires_grad=True)


In [14]:
preds=model(inputs)
loss=mse(targets,preds)
print(loss)

tensor(34632.8398, grad_fn=<DivBackward0>)


In [15]:
#train for 100 epoch
for i in range(100):
    preds=model(inputs)
    loss=mse(targets,preds)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [16]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(122.6491, grad_fn=<DivBackward0>)


In [17]:
#final predictions
print(preds)
print(targets)

tensor([[ 60.0527,  66.4725],
        [ 81.3615,  95.8386],
        [115.9788, 150.1163],
        [ 35.9756,  14.0446],
        [ 92.0840, 124.2279]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
